/**
 * Purdue CS 180 Spring 2014
 * Lab 3
 * 
 * Sample implementation of StringManipulator
 * 
 * @author Your Name <yourUserId@purdue.edu>
 */
 
/**
 * Assign username and email id, given the fullname of the person and the domain.
 */
 
 import java.util.*;
 import java.lang.*;
public class StringManipulator {
 
  /**
   * Make a username out of a person's fullname (first and last only, separated by
   * a space).
   *
   * This method accepts a String as an argument. This String represents a
   * person's fullname, e.g. "John Doe" or "Ann Smith".
   *
   * The fullname is passed as an argument to this method from main.
   * 
   * Your method should return the entire username in lowercase regardless of
   * the case of the input. For example, the input "JOHN DOE" should return
   * "jdoe" and not "JDOE".
   * 
   * HINT: If the name is "John Doe", get first letter with substring method
   *       ("J"), get substring after the space until the end of the string 
   *       ("Doe"), concatenate them together ("JDoe"), and make them in 
   *       lowercase ("jdoe").
   * 
   * @param name
   *            fullname, this parameter contains the person's first and last name separated by a space
   * @return username
   *            username generated by this method.
   */
 
  public String makeUsername(String name) {
      String fUsernameini = name.substring(0,1);
      String fUsernamefin = fUsernameini + name.substring(name.indexOf(' ') + 1);
      return fUsernamefin;
  }
 
 
  /**
   * Make an email address out of the username and the domain
   *
   * This method takes the username and an Internet domain as arguments, 
   * e.g. "jdoe" and "purdue.edu" and returns an email address, 
   * e.g. "jdoe@purdue.edu".
   *
   * The username and the domain are passed as arguments to this method from main.
   * The email address must be in all lowercase, regardless of the case
   * of the domain. For example, the input ("jdoe", "Purdue.EDU")
   * should return "jdoe@purdue.edu", not "jdoe@Purdue.EDU". 
   * 
   * @param name
   *            username returned by the makeUsername method
   * @param domain
   *            Internet domain name (e.g. purdue.edu)
   * @return email
   *            Email address generated
   */
 
  //public String makeEmail(String name, String domain) {
    //  String finalDomainName = name + '@' + domain;
      //return finalDomainName.toLowerCase();
  //}  
 
 
    /**
   * Writing the main() method
   *
   * This method accepts two input strings from the user, which are: fullname and domain
   * fullname: This is the full name of the person, first name followed by last name
   * domain: Name of the internet domain to be used to create the email id
   *
   * The main method calls the makeUsername and makeEmail methods one after another 
   * with appropriate parameters.
   * 
   * The values returned by these methods are printed onto the console.
   * 
   * Look at the sample output below and use appropriate print statements within main
   */
 
  public static void main(String[] args) {    
    // YOUR CODE GOES HERE.
      String uName;
      String domain;
      
      Scanner s = new Scanner(System.in);
      System.out.println("Enter the Full Name. First name followed by Last name: ");
      uName = s.nextLine();
      System.out.println("Enter the Domain: ");
      domain = s.nextLine();
      StringManipulator mPl = new StringManipulator();
      System.out.println("Your username is: " + (mPl.makeUsername(uName).toLowerCase()) + "\nYour email is: " + (mPl.makeUsername(uName).toLowerCase() + '@' + domain).toLowerCase());      
    }
}